### ISSUE TITLE
crash if partkeepr import file has unknown category

### ISSUE THREAD

**Issue by MightyPork** [rhaamo/StockazIO#358]
eg if you have a typo in category name

```
(venv) [stockazio@melon api]$ python3 manage.py import_partkeepr --file importfiles/foo.csv -v3
Common config included
2022-02-12 21:03:03,993 stockazio_api.config INFO     Loaded env file at /home/stockazio/stockazio/.env
PRODUCTION config included
Importing from 'importfiles/foo.csv'
Traceback (most recent call last):
  File "/home/stockazio/stockazio/api/manage.py", line 23, in <module>
    main()
  File "/home/stockazio/stockazio/api/manage.py", line 19, in main
    execute_from_command_line(sys.argv)
  File "/home/stockazio/venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 425, in execute_from_command_line
    utility.execute()
  File "/home/stockazio/venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 419, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/stockazio/venv/lib/python3.10/site-packages/django/core/management/base.py", line 373, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/stockazio/venv/lib/python3.10/site-packages/django/core/management/base.py", line 417, in execute
    output = self.handle(*args, **options)
  File "/home/stockazio/stockazio/api/controllers/part/management/commands/import_partkeepr.py", line 50, in handle
    category = Category.objects.get(name=row["category.name"])
  File "/home/stockazio/venv/lib/python3.10/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/stockazio/venv/lib/python3.10/site-packages/django/db/models/query.py", line 439, in get
    raise self.model.DoesNotExist(
controllers.categories.models.Category.DoesNotExist: Category matching query does not exist.
```

it does not say what line it failed at, maybe it could print each line as it's being imported so you know where it failed.

**Comment by rhaamo** [comment]
Fixed in 7d8b727

```
Working on line: {'name': 'LH154J', 'description': '', 'comment': '', 'stockLevel': '1', 'minStockLevel': '0', 'status': '', 'needsReview': 'false', 'partCondition': '', 'productionRemarks': '', 'internalPartNumber': '', 'category.name': '3 Octocouplers', 'category.categoryPath': '', 'footprint.name': '', 'footprint.category.name': '', 'partUnit.name': '', 'storageLocation.name': '', 'storageLocation.category.name': ''}

Working on line: {'name': 'ADM690', 'description': '', 'comment': '', 'stockLevel': '2', 'minStockLevel': '0', 'status': '', 'needsReview': 'false', 'partCondition': '', 'productionRemarks': '', 'internalPartNumber': '', 'category.name': 'Supervisors', 'category.categoryPath': '', 'footprint.name': '', 'footprint.category.name': '', 'partUnit.name': '', 'storageLocation.name': '', 'storageLocation.category.name': ''}
Category named 'Supervisors' does not exists
```
