### ISSUE TITLE
js error when refreshing category page

### ISSUE THREAD

**Issue by MightyPork** [rhaamo/StockazIO#379]
go to any category `/parts/category/xxx` and refresh the page

```
vue.runtime.esm.js:1897 TypeError: Cannot read properties of undefined (reading 'id')
    at o.vr (List.vue?ae21:1:769)
    at o.e._render (vue.runtime.esm.js:3569:22)
    at o.n (vue.runtime.esm.js:4081:21)
    at rn.get (vue.runtime.esm.js:4495:25)
    at new rn (vue.runtime.esm.js:4484:12)
    at Tr (vue.runtime.esm.js:4088:3)
    at o.Cn.$mount (vue.runtime.esm.js:8459:10)
    at init (vue.runtime.esm.js:3137:13)
    at r (vue.runtime.esm.js:3322:5)
    at f (vue.runtime.esm.js:6022:9)
```

**Comment by rhaamo** [comment]
do you have latest pull ? I think I had fixed that this morning

**Comment by MightyPork** [comment]
yeah I updated just 5 minutes ago, 3a3dc32e50c560d059530de2701c2d9e55ead1e9

**Comment by rhaamo** [comment]
wut, and rebuilt the frontend ? I don't have that issue in dev :/

**Comment by rhaamo** [comment]
oh, happens only on reload, will look

**Comment by MightyPork** [comment]
yeah it's ok when vue opens the page, but fresh load fails

**Comment by rhaamo** [comment]
should be fixed for now

**Comment by MightyPork** [comment]
it loads much slower, but the bug is fixed :+1:

**Comment by rhaamo** [comment]
about loading time yes, I finally fixed the preloadings to be ran before the Vue app is mounted which means first access feels slower.
working to see how I can speedup a bit the calls
